name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          # ensure test helpers are present
          pip install httpx email-validator

      - name: Run backend smoke test
        working-directory: ${{ github.workspace }}
        run: |
          # run the verbose smoke test that exercises signup/login/protected endpoint
          python3 backend/tests_smoke_verbose.py

      - name: List DB file (for debugging)
        if: always()
        run: ls -la | sed -n '1,200p'

