name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint stub
        run: echo "Lint OK"
      - name: Test stub
        run: echo "Tests OK "
